name: deploy-simplest-microservice

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repository to container
        uses: actions/checkout@v1
      - name: build project to jar
        run: mvn -B clean package -DskipTests
      - name: Log current directory 
        run: ls
      - name: Upload jar to tmp share
        uses: actions/upload-artifact@v2
        with:
          name: jarfile
          path: target/demo-0.0.1-SNAPSHOT.jar
      - name: Run jar
      - run: java -jar target/demo-0.0.1-SNAPSHOT.jar
