name: deploy-simplest-microservice

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://adoptopenjdk/openjdk11
      volumes:
      - /workspace:/github/workspace
    steps:
      - uses: actions/checkout@v1
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - run: ls
